name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npx cypress install  # Ensure Cypress is installed

      - name: Run Cypress tests
        run: npx cypress run

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless --verbose

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
        run: npx cypress run --browser chrome --headless

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
